### ISSUE TITLE
_init_ got an unexpected value 'reduction'

### ISSUE THREAD

**Issue by asgq123** [andy-yun/pytorch-0.4-yolov3#40]
which version of pytorch do you use?
I use pytorch0.4 with cuda 9.0 and meet this error ,It says pytorch 0.4.1 may work?appreciate for your reply

**Comment by andy-yun** [comment]
@qiyayun would you give me the detailed error message?
It worked on pytorch 0.4 or over. I recently tested the model on pytorch 1.0.

**Comment by asgq123** [comment]
I train my model and set my data as VOC2007,when I start ,It shows _init_ got an unexpected keyword argument 'reduction'  , it is from yololayer.py  MSELOSS('reduction'=sum).

**Comment by asgq123** [comment]
I'll try to upgrate my pytorch to 0.4.1 ,thanks a lot

**Comment by asgq123** [comment]
pytorch0.4.1 works well!
